### ISSUE TITLE
Getting this error: "Uncaught TypeError: Cannot read property 'path' of undefined"

### ISSUE THREAD

**Issue by halhenke** [klorenz/atom-xikij#4]
Basically on every attempt to evaluate something.

Seems to be related to the fact that in Atom 0.188 projects now have multiple paths?

`atom.project.rootDirectories`
vs 
`atom.project.rootDirectory.path`

-------

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-xikij](https://github.com/klorenz/atom-xikij) package, v0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/Hal/.atom/packages/atom-xikij/lib/editor-request.coffee:21

TypeError: Cannot read property 'path' of undefined
  at EditorRequest.request (/Users/Hal/.atom/packages/atom-xikij/lib/editor-request.coffee:21:48)
  at EditorRequest.expand (/Users/Hal/.atom/packages/atom-xikij/lib/editor-request.coffee:168:6)
  at EditorRequest.run (/Users/Hal/.atom/packages/atom-xikij/lib/editor-request.coffee:296:13)
  at Object.module.exports.toggleContent (/Users/Hal/.atom/packages/atom-xikij/lib/xikij.coffee:174:11)
  at atom-workspace.<anonymous> (/Users/Hal/.atom/packages/atom-xikij/lib/xikij.coffee:22:49)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:22.9 pane:show-next-item (div.settings-view.pane-item)
     -0:21.5 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:19.7 core:confirm (atom-text-editor.editor.mini)
     -0:19.7 tree-view:rename (atom-text-editor.editor.is-focused)
     -0:18.5 core:move-right (atom-text-editor.editor.mini)
     -0:17.9 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini)
     -0:15.8 core:confirm (atom-text-editor.editor.mini)
  4x -0:13.9 core:move-up (atom-text-editor.editor.is-focused)
     -0:13.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:11.6 xikij:run (atom-text-editor.editor.is-focused)
     -0:09.5 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.2 xikij:run (atom-text-editor.editor.is-focused)
     -0:04.4 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.9 xikij:run-with-prompt (atom-text-editor.editor.is-focused)
     -0:02.8 xikij:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "repeat-command",
      "linter-rubocop",
      "tab-switcher",
      "linter-hlint",
      "terminal-runner"
    ],
    "themes": [
      "isotope-ui",
      "material-design-syntax"
    ]
  },
  "atom-xikij": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.2
angularjs, v0.1.0
atom-beautify, v0.23.0
atom-jasmine, v0.5.0
atom-speech-to-code, v0.3.0
atom-terminal-panel, v4.3.1
atom-xikij, v0.9.0
atomatigit, v1.2.3
autocomplete-plus, v2.6.0
coffee-compile, v0.11.0
coffee-lint, v0.7.3
color-picker, v1.5.0
command-logger, v0.22.0
dash, v1.1.0
editorconfig, v0.3.3
expand-selection-to-quotes, v0.1.0
figlet, v0.3.1
file-types, v0.3.0
gulp-snippets, v0.6.1
isotope-ui, v1.7.0
javascript-snippets, v1.0.0
jslint, v1.2.1
language-FBP, v0.1.0
language-ansible, v0.22.0
language-applescript, v0.1.0
language-coffee-script-angular, v2.2.0
language-docker, v1.1.3
language-fish-shell, v1.0.1
language-haml, v0.17.0
language-haskell, v1.0.0
language-ini, v1.9.0
language-jade, v0.3.0
language-tcl, vundefined
line-jumper, v0.13.0
linter, v0.12.0
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
live-editor-reload, v0.1.0
material-design-syntax, v1.6.0
pain-split, v1.3.1
pretty-json, v0.3.2
project-manager, v1.15.5
quick-move-file, v0.7.0
react, v0.10.1
regex-railroad-diagram, v0.7.1
remote-edit, v1.7.2
remote-sync, v2.4.0
ruby-block-converter, v3.3.0
script, v2.18.0
set-syntax, v0.2.1
tabs-to-spaces, v0.9.0
word-jumper, v0.2.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by klorenz** [comment]
Hi Hal,

I have this error, if I try xikij on a "untitled" page.  I fix this in next release.

Best regards, Kiwi

Am 25.03.2015 um 07:47 schrieb Hal Henke:
